
tasks:
  - name: initialize
    before: |

      echo "🚀 before"


    init: |
      echo "🚀 initialize"
      npm install

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - aaron-bond.better-comments
